name: "Test"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: &paths
      - ".github/workflows/test.yaml"
      - "src/**"
      - "package*.json"
      - "*.config.ts"
  pull_request:
    branches: [master]
    paths: *paths

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node 24"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Install"
        id: install
        run: npm ci

      - name: "Test GitHub"
        env:
          MIN_LENGTH: 2
        run: |
          npx get-contributors cssnr/vitepress-plugin-contributors
          echo "::group::cat .vitepress/contributors.json"
          cat .vitepress/contributors.json
          echo "::endgroup::"

          LENGTH=$(jq 'length' .vitepress/contributors.json)
          if [ "$LENGTH" -lt "$MIN_LENGTH" ]; then
            echo "❌ $LENGTH is less than $MIN_LENGTH"
            exit 1
          fi
          echo "✅ Contributors Length: $LENGTH"

      - name: "Test Forgejo"
        env:
          MIN_LENGTH: 3
        run: |
          npx get-contributors -F codeberg.org forgejo-contrib/forgejo-cli
          echo "::group::cat .vitepress/contributors.json"
          cat .vitepress/contributors.json
          echo "::endgroup::"

          LENGTH=$(jq 'length' .vitepress/contributors.json)
          if [ "$LENGTH" -lt "$MIN_LENGTH" ]; then
            echo "❌ $LENGTH is less than $MIN_LENGTH"
            exit 1
          fi
          echo "✅ Contributors Length: $LENGTH"
